### ISSUE TITLE
Coding error

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_entities#2]
Coding error detected, it must be fixed by a programmer: Missing implementation method local_entities_external::list_all_entities

```

Stack trace:

    line 103 of /lib/externallib.php: coding_exception thrown
    line 199 of /admin/webservice/forms.php: call to external_api::external_function_info()
    line 214 of /lib/formslib.php: call to external_service_functions_form->definition()
    line 60 of /admin/webservice/service_functions.php: call to moodleform->__construct()
```

URL: http://localhost/moodle/admin/webservice/service_functions.php?sesskey=eKCKrPat3B&id=9&action=add

**Comment by georgmaisser** [comment]
pretty sure this was fixed some time ago
