### ISSUE TITLE
Database schema is not correct

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_entities#7]
bogner@golf:/var/www/html$ sudo -u www-data php admin/cli/check_database_schema.php 
-------------------------------------------------------------------------------
local_entities
 * column 'pricefactor' has default '1', expected '0' (N)

Fix in upgrade.php

**Comment by bernhard-wunderbyte** [comment]
Pricefactor default needs to be '1'. In the install.xml it had default '0' which was wrong (and would cause all prices to change to 0 if factor is used!)
